name: Python application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest vcrpy python-decouple
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 fouryousee --count --select=E9,F63,F7,F82 --ignore=F401 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 fouryousee --count --exit-zero --max-complexity=10 --ignore=F401 --max-line-length=140 --statistics
    - name: Tests
      env:
        TOKEN: ${{ secrets.TOKEN_4UC_MANAGER }}
      run: |
        pytest
        
